package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logger",
    hdrs = ["logger.h"],
    srcs = ["logger.cpp"],
    deps = [
        "@log4cplus//:log4cplus",
        "@com_github_gflags_gflags//:gflags",
    ],
)