cc_library(
    name = "func",
    hdrs = [
        "func.h",
    ],
    srcs = ["func.cc"],
    deps = [
        "@com_github_gflags_gflags//:gflags",
    ],
    visibility = ["//visibility:public"],
)