cc_binary(
    name = "server_example",
    srcs = [
        "server.cc",
    ],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
        "//proto:helloworld_cc_grpc",
        "@com_github_grpc_grpc//:grpc++_reflection",

    ],
)