workspace(name="bazel_example")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


local_repository(
    name = "sub_bazel_program",
    path = "thirdparty/sub_bazel_program",
)

new_local_repository(
    name = "sub_cmake_program",
    build_file = "thirdparty/sub_cmake_program.BUILD",
    path = "thirdparty/sub_cmake_program"
)

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    tag = "release-1.8.1",
)

git_repository(
    name = "glog",
    remote = "https://github.com/google/glog.git",
    tag = "v0.4.0",
)

git_repository(
    name = "com_github_gflags_gflags",
    remote = "https://github.com/gflags/gflags.git",
    tag = "v2.2.2",
)

# http_archive(
#     name = "temp",
#     sha256 = "akshaksdja",
#     urls = ["file:////data/program/xxx"],
# )